// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateTodo(arg1:main.todo):Promise<main.todo>;

export function DeleteTodo(arg1:main.todo):Promise<main.todo>;

export function Greet(arg1:string):Promise<string>;

export function ListTodos():Promise<Array<main.todo>>;

export function UpdateTodo(arg1:main.todo):Promise<main.todo>;
